language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
install: npm install
script:
  - npm run clean && npm run build
  - npm run lint
  - npm run cover
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - 'uwdub:Ry6mwlUX1aZevqiqmYLiA3N1'
    on_success: never
    on_failure: change
