blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/tags/vega-lite
    about: Please ask questions on Stack Overflow (https://stackoverflow.com/tags/vega-lite), on Slack (https://bit.ly/join-vega-slack-2022), or on [the mailing list](https://bit.ly/vega-discuss).
