name: Test

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Tests
        run: yarn jest test/

      - name: Example tests
        run: yarn jest examples/

      - name: Build
        run: yarn build

  build-site:
    runs-on: ubuntu-latest

    name: Build Site

    steps:
      - uses: actions/checkout@v2

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:site

  runtime-coverage:
    runs-on: ubuntu-latest

    name: Runtime and Coverage

    steps:
      - uses: actions/checkout@v2

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:only

      - name: Runtime tests
        run: yarn test:runtime

      - name: Test coverage
        run: yarn jest test/ --collectCoverage=true

      - name: Upload coverage to Codecov
        run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: CLI

    steps:
      - uses: actions/checkout@v2

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:only

      - name: Compile Vega
        run: |
          bin/vl2vg examples/specs/bar.vl.json -p > bar.vg.json
          cat bar.vg.json

      - name: Diff compiled Vega
        run: diff bar.vg.json examples/compiled/bar.vg.json

      - name: Compile PNG, SVG, PDF
        run: |
          bin/vl2png examples/specs/bar.vl.json > bar.png
          bin/vl2svg examples/specs/bar.vl.json > bar.svg
          bin/vl2pdf examples/specs/bar.vl.json > bar.pdf

      - name: Compile with stdin
        run: cat examples/specs/bar.vl.json | bin/vl2vg -p > bar-stdin.vg.json
